name: CI

on: push

jobs:
  test:
    name: Test installation using `fisher`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fish-actions/install-fish@v1
      - run: |
          curl -sL https://git.io/fisher | source
          fisher install $GITHUB_WORKSPACE
        shell: fish {0}
